# Generated by Django 2.0 on 2018-12-12 16:26

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间')),
                ('question', models.CharField(max_length=124, verbose_name='问题')),
                ('answer', tinymce.models.HTMLField(verbose_name='解答')),
                ('state', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='问题状态')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'db_table': 'faq',
            },
        ),
    ]
